=== 4dtoWakandaGuy/4D_Daybook/Resources/Data/COATEMPLATES/ACCOUNTS.dtd
<?xml version="1.0" encoding="UTF-8"?><!--DTD generated by 4D Application--><!ELEMENT Report_Heading (#PCDATA)><!ELEMENT Account_Code (#PCDATA)><!ELEMENT Account_Name (#PCDATA)><!ELEMENT PB (#PCDATA)><!ELEMENT IO (#PCDATA)><!ELEMENT Group_Heading (#PCDATA)><!ELEMENT No_NL_Postings (#PCDATA)><!ELEMENT Multicurrency_Valuation (#PCDATA)><!ELEMENT xLayerCodes (#PCDATA)><!ELEMENT xAnalysisCodes (#PCDATA)><!ELEMENT ACCOUNTS (Report_Heading?, Account_Code?, Account_Name?, PB?, IO?, Group_Heading?, No_NL_Postings?, Multicurrency_Valuation?, xLayerCodes?, xAnalysisCodes?)><!ELEMENT Root (ACCOUNTS*)>

=== 4dtoWakandaGuy/4D_Daybook/Resources/Data/COATEMPLATES/LEISURE_ACCOUNTS.xml
<?xml version="1.0" encoding="UTF-8"?><!--Created by 4D Application --><!DOCTYPE Root SYSTEM "ACCOUNTS.dtd"><Root><ACCOUNTS>		<Report_Heading>B1A</Report_Heading>		<Account_Code>11001</Account_Code>		<Account_Name>Checking Wells Fargo</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes>data:;base64,UlZMQiIAAAAAAAAAAAAAAAA=</xLayerCodes>		<xAnalysisCodes>data:;base64,UlZMQiIAAAAAAAAAAAAAAAA=</xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1A</Report_Heading>		<Account_Code>11002</Account_Code>		<Account_Name>MMA Wells Fargo</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1A</Report_Heading>		<Account_Code>11010</Account_Code>		<Account_Name>Societe Generale FF Account</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1A</Report_Heading>		<Account_Code>11020</Account_Code>		<Account_Name>US Bank Checking Account</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1A</Report_Heading>		<Account_Code>11025</Account_Code>		<Account_Name>Ruesch  Int./ AFEX</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes>data:;base64,QkxWUhUAAAAAAAAAAAAMAAAAAAAAAAAAAAAA</xLayerCodes>		<xAnalysisCodes>data:;base64,QkxWUhUAAAAAAAAAAAAMAAAAAAAAAAAAAAAA</xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1A</Report_Heading>		<Account_Code>11030</Account_Code>		<Account_Name>Petty Cash</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1B</Report_Heading>		<Account_Code>12001</Account_Code>		<Account_Name>Trade Accounts Receivable</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1B</Report_Heading>		<Account_Code>12002</Account_Code>		<Account_Name>Other  Receivable-JF/Marketing</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1B</Report_Heading>		<Account_Code>12003</Account_Code>		<Account_Name>Loans to EM</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1B</Report_Heading>		<Account_Code>12004</Account_Code>		<Account_Name>Other Receivable-JF/Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1B</Report_Heading>		<Account_Code>12005</Account_Code>		<Account_Name>Loans to Third Parties</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1B</Report_Heading>		<Account_Code>12009</Account_Code>		<Account_Name>Allowance For Doubtful Accts</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13010</Account_Code>		<Account_Name>Exclusive RR Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13011</Account_Code>		<Account_Name>Gros Grain Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13012</Account_Code>		<Account_Name>Jacquard Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13013</Account_Code>		<Account_Name>Metallic Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13014</Account_Code>		<Account_Name>Novelty/Apparel Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13015</Account_Code>		<Account_Name>Passementeries Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13016</Account_Code>		<Account_Name>Sparkling Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13017</Account_Code>		<Account_Name>Vintage Jacquard Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13018</Account_Code>		<Account_Name>Personalize Ribbons Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes>data:;base64,QkxWUhUAAAAAAAAAAAAMAAAAAAAAAAAAAAAA</xLayerCodes>		<xAnalysisCodes>data:;base64,QkxWUhUAAAAAAAAAAAAMAAAAAAAAAAAAAAAA</xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13019</Account_Code>		<Account_Name>Wired/ Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes>data:;base64,QkxWUhUAAAAAAAAAAAAMAAAAAAAAAAAAAAAA</xLayerCodes>		<xAnalysisCodes>data:;base64,QkxWUhUAAAAAAAAAAAAMAAAAAAAAAAAAAAAA</xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13020</Account_Code>		<Account_Name>Miscellaneous Ribbon Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13022</Account_Code>		<Account_Name>Kafka Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Report_Heading>		<Account_Code>13023</Account_Code>		<Account_Name>Vintage Wired Ribbons Inventory</Account_Name>		<PB>B</PB>		<IO>N</IO>		<Group_Heading>GB1</Group_Heading>		<No_NL_Postings>false</No_NL_Postings>		<Multicurrency_Valuation>0</Multicurrency_Valuation>		<xLayerCodes></xLayerCodes>		<xAnalysisCodes></xAnalysisCodes>	</ACCOUNTS><ACCOUNTS>		<Report_Heading>B1C</Rep
