=== 4dtoWakandaGuy/4D_Daybook/Resources/Data/COATEMPLATES/HEADINGS.dtd
<?xml version="1.0" encoding="UTF-8"?><!--DTD generated by 4D Application--><!ELEMENT Heading_Code (#PCDATA)><!ELEMENT Heading_Name (#PCDATA)><!ELEMENT Heading_Level (#PCDATA)><!ELEMENT Level_Up_Code (#PCDATA)><!ELEMENT Group_Code (#PCDATA)><!ELEMENT AccCodeRangeFrom (#PCDATA)><!ELEMENT AccCodeRangeTo (#PCDATA)><!ELEMENT EnforceRange (#PCDATA)><!ELEMENT HEADINGS (Heading_Code?, Heading_Name?, Heading_Level?, Level_Up_Code?, Group_Code?, AccCodeRangeFrom?, AccCodeRangeTo?, EnforceRange?)><!ELEMENT Root (HEADINGS*)>

=== 4dtoWakandaGuy/4D_Daybook/Resources/Data/COATEMPLATES/LEISURE_HEADINGS.xml
<?xml version="1.0" encoding="UTF-8"?><!--Created by 4D Application --><!DOCTYPE Root SYSTEM "HEADINGS.dtd"><Root><HEADINGS>		<Heading_Code>P2L</Heading_Code>		<Heading_Name>Inventory Adjustments</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P6A</Heading_Code>		<Heading_Name>Related Income &amp; Expenses</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P6</Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P6B</Heading_Code>		<Heading_Name>Other Income &amp; Expenses</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P6</Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P6</Heading_Code>		<Heading_Name>Financial</Heading_Name>		<Heading_Level>1</Heading_Level>		<Level_Up_Code></Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P5</Heading_Code>		<Heading_Name>Administration Expenses</Heading_Name>		<Heading_Level>1</Heading_Level>		<Level_Up_Code></Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P4</Heading_Code>		<Heading_Name>Labor</Heading_Name>		<Heading_Level>1</Heading_Level>		<Level_Up_Code></Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P3E</Heading_Code>		<Heading_Name>Other Sales &amp; Marketing Expenses</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P3</Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P3D</Heading_Code>		<Heading_Name>Buying Expenses</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P3</Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P3C</Heading_Code>		<Heading_Name>Marketing Expenses</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P3</Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P3B</Heading_Code>		<Heading_Name>Sales Expenses</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P3</Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P3</Heading_Code>		<Heading_Name>Sales &amp; Marketing</Heading_Name>		<Heading_Level>1</Heading_Level>		<Level_Up_Code></Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2J</Heading_Code>		<Heading_Name>Expenses Recovered From Client</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P3A</Heading_Code>		<Heading_Name>Sales Commission</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P3</Level_Up_Code>		<Group_Code>GP2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2K</Heading_Code>		<Heading_Name>Purchase Fees and Discount</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2G</Heading_Code>		<Heading_Name>Purchases - Shipping &amp; Exporting Outbound</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2F</Heading_Code>		<Heading_Name>Purchases - Shipping &amp; Importing Inbound</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2E</Heading_Code>		<Heading_Name>Purchases - Miscellaneous</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2D</Heading_Code>		<Heading_Name>Purchases - Ribbon Books</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2C</Heading_Code>		<Heading_Name>Purchases - Ribbon Club</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2B</Heading_Code>		<Heading_Name>Purchases - Ribbons</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P2</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P2</Heading_Code>		<Heading_Name>Cost of Goods Sold</Heading_Name>		<Heading_Level>1</Heading_Level>		<Level_Up_Code></Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P1E</Heading_Code>		<Heading_Name>Income - Other</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P1</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P1D</Heading_Code>		<Heading_Name>Sales - Miscellaneous</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P1</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P1C</Heading_Code>		<Heading_Name>Sales - Book</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P1</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P1B</Heading_Code>		<Heading_Name>Sales - Ribbon Club</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P1</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P1A</Heading_Code>		<Heading_Name>Sales - Ribbons</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>P1</Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>P1</Heading_Code>		<Heading_Name>Sales</Heading_Name>		<Heading_Level>1</Heading_Level>		<Level_Up_Code></Level_Up_Code>		<Group_Code>GP1</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>B6</Heading_Code>		<Heading_Name>Equity</Heading_Name>		<Heading_Level>1</Heading_Level>		<Level_Up_Code></Level_Up_Code>		<Group_Code>GB2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>B5</Heading_Code>		<Heading_Name>Long Term Liabilities</Heading_Name>		<Heading_Level>1</Heading_Level>		<Level_Up_Code></Level_Up_Code>		<Group_Code>GB2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>B4D</Heading_Code>		<Heading_Name>Short Term Liabilities</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>B4</Level_Up_Code>		<Group_Code>GB2</Group_Code>		<AccCodeRangeFrom></AccCodeRangeFrom>		<AccCodeRangeTo></AccCodeRangeTo>		<EnforceRange>0</EnforceRange>	</HEADINGS><HEADINGS>		<Heading_Code>B4C</Heading_Code>		<Heading_Name>Accruals &amp; Deposits</Heading_Name>		<Heading_Level>2</Heading_Level>		<Level_Up_Code>B4</Level_Up_Code>		<Group_Code>GB2</Group_Code>		<AccCodeRangeFrom>
